/**
 * AIEngineeringTab.jsx — AI Code % and AI Test % page
 * Displays AI-generated share metrics for engineering.
 * Extracted from RideHailingTab's AISection per user request.
 *
 * NOTE: Data is currently static (week of Aug 3–9).
 * When a live BigQuery source is connected, replace the static values below.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Design tokens
// ─────────────────────────────────────────────────────────────────────────────
const T = {
  bg:'#ffffff', bg2:'#FAFBFC', bg3:'#F1F5F9', bg4:'#E2EAF0',
  text:'#1A2B3C', text2:'#374151', text3:'#64748B',
  border:'#E2EAF0', border2:'#B8C4D0',
  green:'#1D9E75', greenBg:'rgba(29,158,117,.11)',
  blue:'#185FA5',
  red:'#E24B4A',
  amber:'#D85A30',
  lift:'0 1px 2px rgba(26,26,24,.05), 0 6px 16px -6px rgba(26,26,24,.10)',
}

const CARD = {
  background:T.bg, borderRadius:12, boxShadow:T.lift,
  border:`1px solid ${T.border}`, padding:'20px 24px 18px',
  flex:1, minWidth:200,
}

// ─────────────────────────────────────────────────────────────────────────────
// Static data (§8.8) — replace with live data when available
// ─────────────────────────────────────────────────────────────────────────────
const AI_METRICS = [
  {
    id: 'ai_code_pct',
    label: 'AI Code %',
    description: 'Share of code commits that are AI-generated',
    current: 93.0,
    prior: 95.70,
    unit: '%',
    lowerIsBetter: false,
  },
  {
    id: 'ai_test_pct',
    label: 'AI Test %',
    description: 'Share of test files generated by AI',
    current: 26.5,
    prior: 44.60,
    unit: '%',
    lowerIsBetter: false,
  },
]

// ─────────────────────────────────────────────────────────────────────────────
// Metric card
// ─────────────────────────────────────────────────────────────────────────────
function MetricCard({ metric }) {
  const delta = metric.current - metric.prior
  const isPositive = metric.lowerIsBetter ? delta <= 0 : delta >= 0
  const deltaColor = isPositive ? T.green : T.red
  const currentColor = isPositive ? T.green : T.red

  // Progress bar — percentage of 100
  const barPct = Math.min(100, Math.max(0, metric.current))

  return (
    <div style={CARD}>
      <div style={{fontSize:10.5,fontWeight:600,color:T.text3,marginBottom:8,textTransform:'uppercase',letterSpacing:'0.06em'}}>
        {metric.label}
      </div>
      <div style={{fontSize:36,fontWeight:700,color:currentColor,lineHeight:1.05}}>
        {metric.current.toFixed(1)}{metric.unit}
      </div>
      <div style={{margin:'10px 0 6px'}}>
        <div style={{height:7,background:T.bg3,borderRadius:4,overflow:'hidden'}}>
          <div style={{
            width:`${barPct}%`,height:'100%',
            background:`linear-gradient(90deg, ${T.blue} 0%, ${currentColor} 100%)`,
            borderRadius:4,transition:'width 0.5s ease',
          }}/>
        </div>
      </div>
      <div style={{fontSize:11.5,color:T.text3,marginBottom:4}}>{metric.description}</div>
      <div style={{fontSize:12,fontWeight:600,color:deltaColor}}>
        {delta >= 0 ? '+' : ''}{delta.toFixed(2)} pts WoW
        <span style={{fontWeight:400,color:T.text3}}> · prior {metric.prior.toFixed(2)}{metric.unit}</span>
      </div>
    </div>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// Weekly trend table (static)
// ─────────────────────────────────────────────────────────────────────────────
const WEEKLY_DATA = [
  { week: 'Aug 3–9',   aiCode: 93.0,  aiTest: 26.5  },
  { week: 'Jul 27–Aug 2', aiCode: 95.70, aiTest: 44.60 },
]

const TH = {padding:'7px 12px',fontSize:10,fontWeight:700,color:T.text3,textTransform:'uppercase',letterSpacing:'0.06em',background:T.bg2,borderBottom:`1px solid ${T.border}`,textAlign:'right',whiteSpace:'nowrap'}
const TD = {padding:'10px 12px',fontSize:13,verticalAlign:'middle',textAlign:'right',fontVariantNumeric:'tabular-nums'}

function WeeklyTable(){
  return (
    <div style={{background:T.bg,borderRadius:12,boxShadow:T.lift,border:`1px solid ${T.border}`,overflow:'hidden',marginTop:24}}>
      <div style={{padding:'12px 16px 10px',borderBottom:`1px solid ${T.border}`}}>
        <div style={{fontWeight:700,fontSize:13.5,color:T.text}}>Week-on-Week History</div>
        <div style={{fontSize:11.5,color:T.text3,marginTop:2}}>Static snapshot — live BigQuery feed not yet connected</div>
      </div>
      <table style={{width:'100%',borderCollapse:'collapse'}}>
        <thead>
          <tr>
            <th style={{...TH,textAlign:'left',paddingLeft:16}}>Week</th>
            <th style={TH}>AI Code %</th>
            <th style={TH}>AI Test %</th>
          </tr>
        </thead>
        <tbody>
          {WEEKLY_DATA.map((row, i) => {
            const codeColor = i === 0 ? (row.aiCode >= (WEEKLY_DATA[1]?.aiCode ?? 0) ? T.green : T.red) : T.text3
            const testColor = i === 0 ? (row.aiTest >= (WEEKLY_DATA[1]?.aiTest ?? 0) ? T.green : T.red) : T.text3
            return (
              <tr key={row.week} style={{borderBottom:`1px solid ${T.border}`,background:i===0?'#F8FAFF':T.bg}}>
                <td style={{...TD,textAlign:'left',paddingLeft:16,fontWeight:i===0?700:400,color:T.text}}>
                  {row.week}{i===0&&<span style={{marginLeft:8,fontSize:10,fontWeight:700,background:T.blue,color:'#fff',borderRadius:8,padding:'1px 7px'}}>Latest</span>}
                </td>
                <td style={{...TD,color:codeColor,fontWeight:i===0?700:400}}>{row.aiCode.toFixed(1)}%</td>
                <td style={{...TD,color:testColor,fontWeight:i===0?700:400}}>{row.aiTest.toFixed(1)}%</td>
              </tr>
            )
          })}
        </tbody>
      </table>
    </div>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// Main component
// ─────────────────────────────────────────────────────────────────────────────
export default function AIEngineeringTab() {
  return (
    <div>
      {/* Header */}
      <div style={{marginBottom:20}}>
        <div style={{display:'flex',alignItems:'center',gap:10,marginBottom:4}}>
          <h1 style={{fontSize:20,fontWeight:700,color:T.text,margin:0}}>AI Code &amp; Test</h1>
          <span style={{
            fontSize:10,fontWeight:700,padding:'2px 8px',borderRadius:10,
            background:'rgba(234,179,8,.15)',color:'#9A6B0C',letterSpacing:'0.06em',
          }}>
            STATIC · AUG 3–9
          </span>
        </div>
        <div style={{fontSize:13,color:T.text3}}>
          Engineering AI-generated share metrics. Week-on-week comparison.
        </div>
      </div>

      {/* Static data notice */}
      <div style={{
        background:'rgba(234,179,8,.10)',border:'1px solid rgba(234,179,8,.5)',
        borderRadius:8,padding:'10px 14px',fontSize:12.5,color:'#9A6B0C',
        marginBottom:20,lineHeight:1.6,
      }}>
        ⚠️ <strong>Static data.</strong> These figures are manually entered for week Aug 3–9.
        A live BigQuery connection for AI engineering metrics is not yet configured.
        When available, this page will auto-refresh with live data.
      </div>

      {/* Metric cards */}
      <div style={{display:'flex',gap:16,flexWrap:'wrap',marginBottom:8}}>
        {AI_METRICS.map(m => <MetricCard key={m.id} metric={m}/>)}
      </div>

      {/* Weekly trend table */}
      <WeeklyTable/>
    </div>
  )
}
